//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukolnik.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ukolnik.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream aoogah {
            get {
                return ResourceManager.GetStream("aoogah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS `udalosti` (`ID` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT, `Typ` TINYINT(1) UNSIGNED NOT NULL, `Nadpis` TEXT NOT NULL, `Zprava` TEXT CHARACTER SET cp1250 COLLATE cp1250_czech_cs, `Kdy` DATETIME NOT NULL, `Splneno` TINYINT(1) UNSIGNED NOT NULL DEFAULT &apos;0&apos;, `Upozorneno` TINYINT(1) UNSIGNED NOT NULL DEFAULT &apos;0&apos;, `Upozorneni` DATETIME NOT NULL, PRIMARY KEY (`ID`)) ENGINE=MYISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT=&apos;1.0.0.0&apos;;
        ///CREATE TABLE IF NOT EXISTS `svatky` (`Datum` TEXT C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon diar {
            get {
                object obj = ResourceManager.GetObject("diar", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fajfka {
            get {
                object obj = ResourceManager.GetObject("fajfka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap krizek {
            get {
                object obj = ResourceManager.GetObject("krizek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `svatky`(`Datum`,`Jmeno`,`Upozornit`) VALUES (&apos;24-12&apos;,&apos;Adam&apos;,0),(&apos;2-9&apos;,&apos;Adéla&apos;,0),(&apos;17-6&apos;,&apos;Adolf&apos;,0),(&apos;26-6&apos;,&apos;Adriana&apos;,0),(&apos;14-10&apos;,&apos;Agáta&apos;,0),(&apos;14-8&apos;,&apos;Alan&apos;,0),(&apos;21-11&apos;,&apos;Albert&apos;,0),(&apos;16-12&apos;,&apos;Albína&apos;,0),(&apos;13-8&apos;,&apos;Alena&apos;,0),(&apos;13-4&apos;,&apos;Aleš&apos;,0),(&apos;27-2&apos;,&apos;Alexandr&apos;,0),(&apos;21-4&apos;,&apos;Alexandra&apos;,0),(&apos;3-5&apos;,&apos;Alexej&apos;,0),(&apos;15-1&apos;,&apos;Alice&apos;,0),(&apos;21-6&apos;,&apos;Alois&apos;,0),(&apos;19-11&apos;,&apos;Alžběta&apos;,0),(&apos;7-12&apos;,&apos;Ambrož&apos;,0),(&apos;15-4&apos;,&apos;Anastázie&apos;,0),(&apos;11-3&apos;,&apos;Anděla&apos;,0),(&apos;26-9&apos;,&apos;Andrea&apos;,0),(&apos;11-10&apos;,&apos;Andrej&apos;,0),(&apos;17-5&apos;,&apos;Aneta&apos;,0),(&apos;2-3&apos;,&apos;Anežka [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string svatky {
            get {
                return ResourceManager.GetString("svatky", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tuzka {
            get {
                object obj = ResourceManager.GetObject("tuzka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `vyznamne_dny`(`Datum`,`Den`,`Poradi`,`Upozornit`) VALUES (&apos;25-12&apos;,&apos;1.svátek vánoční&apos;,1,0),(&apos;26-12&apos;,&apos;2.svátek vánoční&apos;,2,0),(&apos;2-11&apos;,&apos;Památka zesnulých&apos;,3,0),(&apos;5-7&apos;,&apos;Státní svátek - Cyril a Metoděj&apos;,4,0),(&apos;17-11&apos;,&apos;Státní svátek - Den boje za svobodu&apos;,5,0),(&apos;8-5&apos;,&apos;Statní svátek - Den vítězství&apos;,6,0),(&apos;6-7&apos;,&apos;Státní svátek - Mistr Jan Hus&apos;,7,0),(&apos;1-5&apos;,&apos;Státní svátek - Svátek práce&apos;,8,0),(&apos;28-9&apos;,&apos;Státní svátek - Svatý Václav&apos;,9,0),(&apos;1-1&apos;,&apos;Státní svátek - Vznik ČR&apos;,10,0),(&apos;28-10&apos;,&apos;Státní svátek - vzni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vyznamne_dny {
            get {
                return ResourceManager.GetString("vyznamne_dny", resourceCulture);
            }
        }
    }
}
